### PR TITLE
vp menu item review delete

### PR DESCRIPTION
**Pull request by vedp3705**
Closes issue #30. Delete fully tested and functional.

### CODE REVIEW

**Review by EduinoMEH — APPROVED** [review]
DELETE endpoint looks good to me, as well as the testing done!

**Comment by vedp3705** [comment]
wait for merge conflicts to be resolved before merging.

**Comment by vedp3705** [comment]
wait for merge conflicts to be resolved before merging.

**Comment by vedp3705** [comment]
all good now.

**Review by billybobjoe123 — APPROVED** [review]
looks good to me

**Pull request merged**
