### PR TITLE
Create database table for articles, Create ArticlesController added GET (index), POST (create) GET(show) PUT(edit) DELETE endpoints

### PR DESCRIPTION
**Pull request by billybobjoe123**
modified files
Articles.java
ArticlesController.java
articlesRepository
ArticlesControllerTests.java
Articles.json

has 100% line coverage and mutation coverage

### CODE REVIEW

**Comment by billybobjoe123** [comment]
javadoc failing? everything else works? 

image

**Comment by billybobjoe123** [comment]
all checks passed. Fixed javadoc issue

**Review by rushil-x-gupta — APPROVED** [review]
all of your tests are passing, should be good!

**Review by EduinoMEH — APPROVED** [review]
All looks good to me, all end points are properly tested!

**Pull request merged**
