### PR TITLE
Created PUT and DELETE endpoints

### PR DESCRIPTION
**Pull request by rushil-x-gupta**
Closes Issues #35 and #36

### CODE REVIEW

**Review by vedp3705 — CHANGES_REQUESTED** [review]
Have you tested for full line and mutation coverage?

**Review by rushil-x-gupta — COMMENTED** [review]
yup, made changes

**Review by vedp3705 — APPROVED** [review]
right branch and passing tests

**Review by vedp3705 — APPROVED** [review]
Look good!

**Review by billybobjoe123 — APPROVED** [review]
looks good, has put and delete, has test cases

**Pull request merged**
